---
- hosts: localhost
  remote_user: root
  become: yes

  tasks:
#    - name: Downloading workbooks (1/3)
#      get_url:
#        url: https://raw.githubusercontent.com/Diadon81/oref0-install/master/playbooks/systeminstall.yml
#        dest: /tmp/systeminstall.yml
#        mode: '0440'
#    - name: Downloading workbooks (2/3)
#      get_url:
#        url: https://raw.githubusercontent.com/Diadon81/oref0-install/master/playbooks/bluetoothinstall.yml
#        dest: /tmp/bluetoothinstall.yml
#        mode: '0440'
#    - name: Downloading workbooks (3/4)
#      get_url:
#        url: https://raw.githubusercontent.com/Diadon81/oref0-install/master/playbooks/openapsinstall.yml
#        dest: /tmp/openapsinstall.yml
#        mode: '0440'
#    - name: Downloading workbooks (4/4)
#      get_url:
#        url: https://raw.githubusercontent.com/Diadon81/oref0-install/master/playbooks/orefinstall.yml
#        dest: /tmp/orefinstall.yml
#        mode: '0440'

    - include_tasks: /tmp/systeminstall.yml
    - include_tasks: /tmp/bluetoothinstall.yml
    - include_tasks: /tmp/openapsinstall.yml
    - include_tasks: /tmp/orefinstall.yml
