---
- hosts: localhost
  remote_user: root
  become: yes


  tasks:
    - name: Installing final packages
      apt:
        name: "{{ item }}"
      with_items:
       - libdbus-1-dev
       - git
       - python
       - python-dev
       - software-properties-common
       - python-numpy
       - python-pip
       - watchdog
       - strace
       - tcpdump
       - screen
       - acpid
       - vim
       - locate
       - jq
       - lm-sensors
       
    - name: Install expect
      apt:
        name: expect
        install_recommends: no

    - name: Installing OpenAPS
      pip:
       name: "{{ item }}"
       extra_args: "-U"
      with_items:
       - openaps
       - openaps-contrib
    - name: Running post-install scripts (1/3)
      shell: "openaps-install-udev-rules"
    - name: Running post-install scripts (2/3)
      shell: "activate-global-python-argcomplete"
    - name: Running post-install scripts (3/3)
      shell: "npm install -g json oref0"
    - name: Checkout oref0 from repository
      git:
       repo: "git://github.com/openaps/oref0.git"
       dest: /root/src/oref0
       version: master
