    - name: Running oref0-setup
      shell: |
       set timeout 3000
       spawn {{ command }}
       send "y\n"
       expect "cron?"
       send "y\n"
       expect "first?"
       send "y\n"
       expect "Reboot"
       send "\n"
      args:
       executable: /usr/bin/expect
       chdir: /root
